### ISSUE TITLE
Secondary account (send email as): does not work

### ISSUE THREAD

**Issue by esseti** [MyOutDeskLLC/OSS-Privacy-Policy#1]
Hello,
I've more than one single account from which I'm able to send emails. 
In settings -> accounts -> Send email as: (there i've two accounts)

The extension works only from the principal email, and not for the second.
In addition, even if I create an email and select my second account as sender, it still applies the rule for the first account.

Do you by any chance ignore this multiple account possibility? is something that can be fixed?

**Comment by WalrusSoup** [comment]
Wrong repo, please post over in the extension itself? https://github.com/MyOutDeskLLC/auto-bcc
